[project]
name = "bilibili-video-content-getter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "bilibili-api-python>=17.1.4",
    "httpx>=0.27.0",
    "mcp[cli]>=1.6.0",
]
